// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/lib/database.types'; 

const SUPABASE_URL = "https://nqbxamptzghyidguvvbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xYnhhbXB0emdoeWlkZ3V2dmJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDkxNTUsImV4cCI6MjA2NTcyNTE1NX0.Zax6A-25wZsfUUzYxOWQB5Aq03Oc0Gulv9tTag0L0W0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);